# Generated by Django 4.2.7 on 2024-05-29 18:08

import datetime
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name="carro",
            name="data_cadastro",
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
