# Generated by Django 4.2.7 on 2024-05-29 18:15

import datetime
from django.utils import timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0002_empresa_alter_carro_data_cadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="data_cadastro",
            field=models.DateTimeField(
                default=timezone.now
            ),
        ),
    ]
